version: '3.8'

services:
  backend:
    image: meditrack-backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/meditrack.db
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    volumes:
      - backend-data:/app/data
    networks:
      - meditrack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: meditrack-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - meditrack-network
    environment:
      - NODE_ENV=production

  # Optional: Database viewer (remove in production)
  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - meditrack-network
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=sqlite

networks:
  meditrack-network:
    driver: bridge

volumes:
  backend-data: