name: Auto-merge Dependabot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    # Note: GitHub Actions cannot approve PRs, so we skip the approval step
    # and go directly to auto-merge, which will merge when all checks pass
        
    - name: Enable auto-merge for Dependabot PR
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment on PR
      run: |
        gh pr comment "$PR_URL" --body "Auto-merge enabled for this Dependabot PR. It will merge automatically once all checks pass.
        
        Update type: ${{ steps.metadata.outputs.update-type }}
        Dependency: ${{ steps.metadata.outputs.dependency-names }}
        Version: ${{ steps.metadata.outputs.previous-version }} → ${{ steps.metadata.outputs.new-version }}"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}