name: Dependabot PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    # Auto-merge is disabled to prevent merging PRs that break the build
    # PRs will need to be manually reviewed and merged
        
    - name: Comment on PR
      run: |
        gh pr comment "$PR_URL" --body "Dependabot update detected.
        
        Update type: ${{ steps.metadata.outputs.update-type }}
        Dependency: ${{ steps.metadata.outputs.dependency-names }}
        Version: ${{ steps.metadata.outputs.previous-version }} → ${{ steps.metadata.outputs.new-version }}
        
        ⚠️ Auto-merge is currently disabled. Please review the changes and test that they don't break the build before merging."
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}